name: Run deprem bot

on:
  workflow_dispatch:
    inputs:
      sehir:
        description: "Bildirim almak istediğiniz şehir"
        required: false
        default: "Kayseri"
      zaman_araligi:
        description: "Bildirim almak istediğiniz zaman aralığı"
        required: false
        default: "10"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run deprem bot
        run: |
          python deprem.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          CITY_TO_BE_CHECKED: ${{ github.event.inputs.sehir }}
          TIME_INTERVAL: ${{ github.event.inputs.zaman_araligi }}
