name: Run deprem bot

on:
  schedule:
    # every 5 minutes
    - cron: "*/5 * * * *"

  workflow_dispatch:
    inputs:
      sehir:
        description: "Bildirim almak istediğiniz şehir"
        required: false
        default: "Kayseri"
      zaman_araligi:
        description: "Bildirim almak istediğiniz zaman aralığı"
        required: false
        default: "5"
env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

permissions:
  contents: read

jobs:
  run_deprem_bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip" # cache pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run deprem bot on demand
        run: |
          python deprem.py
        env:
          CITY_TO_BE_CHECKED: "${{ github.event.inputs.sehir }}"
          TIME_INTERVAL: ${{ github.event.inputs.zaman_araligi }}

      - name: Run deprem bot on schedule
        if: ${{ github.event_name == 'schedule' }}
        run: |
          python scheduled.py
        env:
          CITY_TO_BE_CHECKED: "Kayseri"
          TIME_INTERVAL: "5"
